server.document-root = "/change/this/server"
server.port = 8080

server.max-worker = 4
server.network-backend = "writev"
server.event-handler = "linux-sysepoll"

# Disable heavy features
server.tag = "lighttpd-benchmark"
server.modules = ( )
mimetype.assign = ( ".html" => "text/html", ".bin" => "application/octet-stream" )

# Turn off logging to avoid disk I/O overhead
accesslog.filename = "/dev/null"
server.errorlog = "/dev/null"